# Generated by Django 3.1.7 on 2021-03-03 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UslugeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_agree', models.BooleanField(default=False)),
                ('is_over18', models.BooleanField(default=False)),
                ('activation_key', models.CharField(max_length=128)),
                ('activation_key_expires', models.DateTimeField(default=datetime.datetime(2021, 3, 5, 11, 24, 22, 817864, tzinfo=utc))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UslugeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_profile', models.CharField(choices=[('IP', 'ИП'), ('OOO', 'ООО'), ('PF', 'Физ. лицо')], default='PF', max_length=3)),
                ('name_profile', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('surname_profile', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('companyname_profile', models.CharField(blank=True, max_length=64, verbose_name='Название компании')),
                ('ogrn_profile', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='ОГРН')),
                ('inn_profile', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='ИНН')),
                ('phone_profile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('photo_profile', models.ImageField(blank=True, default='photos_profiles/default.jpg', upload_to='photos_profiles', verbose_name='Фото')),
                ('address_profile', models.CharField(blank=True, max_length=80, verbose_name='Адресс')),
                ('country_profile', models.CharField(blank=True, max_length=32, verbose_name='Страна')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
