# Generated by Django 3.1.7 on 2021-03-10 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 14, 13, 59, 889811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='inn_profile',
            field=models.SmallIntegerField(blank=True, default=None, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='ogrn_profile',
            field=models.SmallIntegerField(blank=True, default=None, verbose_name='ОГРН'),
        ),
    ]
