# Generated by Django 3.1.7 on 2021-03-10 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210310_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 14, 15, 46, 685091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='inn_profile',
            field=models.CharField(blank=True, max_length=64, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='ogrn_profile',
            field=models.CharField(blank=True, max_length=64, verbose_name='ОГРН'),
        ),
    ]
