# Generated by Django 3.1.7 on 2021-03-13 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210310_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 14, 45, 8, 88651, tzinfo=utc)),
        ),
    ]
