# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210313_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uslugeuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='uslugeuser',
            name='activation_key_expires',
        ),
    ]
