# Generated by Django 3.1.7 on 2021-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210313_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='inn_profile',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ИНН'),
        ),
    ]
