# Generated by Django 3.1.7 on 2021-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210313_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='inn_profile',
            field=models.CharField(blank=True, max_length=64, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='ogrn_profile',
            field=models.CharField(blank=True, max_length=64, verbose_name='ОГРН'),
        ),
    ]
