# Generated by Django 3.1.7 on 2021-03-13 16:55

import authapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20210313_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugeuserprofile',
            name='user_profile',
            field=models.OneToOneField(default=authapp.models.UslugeUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
